### PR TITLE
Add PlotnineAnimation

### PR DESCRIPTION
**Pull request by has2k1**

### CODE REVIEW

**Comment by has2k1** [comment]
@gokceneraslan, can you try this out.

See the [example](https://github.com/has2k1/plotnine-examples/blob/master/plotnine_examples/examples/PlotnineAnimation.ipynb)

Thanks.

**Comment by has2k1** [comment]
Ping @gokceneraslan.

**Comment by gokceneraslan** [comment]
I tried it with the following code:

```python
from plotnine import *
from plotnine.data import *
from plotnine.animation import PlotnineAnimation

import numpy as np

def plot(y):
    return (qplot(y[:, 0], y[:, 1], xlab='x', ylab='y') +
            theme_minimal())

# Use mtcars as toy data
X = mtcars[['disp', 'hp']].as_matrix()

# Add little noise to make animation cool
data = [X+np.random.normal(0, 1, (X.shape[0], X.shape[1])) for _ in range(50)]

figs = [plot(x) for x in data]
ani = PlotnineAnimation(figs, interval=100, repeat_delay=500)
ani.save('/tmp/animation.mp4')
```

and it looks really amazing, thanks a lot! #45 can be closed now, I guess.

**Comment by has2k1** [comment]
Do you find the docstring instructions clear enough? Specifically the **Note** stuff. If not understood it is easy to create an inaccurate/wrong animation.

**Comment by gokceneraslan** [comment]
I think it's clear. It'd be even better to have a mechanism to check whether scales are consistent and print a warning/error, if not.

By the way, did you by any chance test this with more "unusual" plots like the ones with geom_text, geom_tile, geom_smooth, facetting etc?

**Comment by has2k1** [comment]
I did consider checking the scales, but I thought it could not be done reliably. Huh, now I think it can be done; I hope it holds up. Thanks.

> By the way, did you by any chance test this with more "unusual" plots like the ones with geom_text, geom_tile, geom_smooth, facetting etc?

facetting, yes. It is not in this PR, in the preparation for this commit there some was a (refactoring)[https://github.com/has2k1/plotnine/commit/796a7db764b395ade9f8d00b7e29579a770e3d3b] that targeted facets. For the rest, I saw no reason to bug hunt.

**Pull request merged**
