### PR TITLE
Adds `caption=` option to `labs`

### PR DESCRIPTION
**Pull request by jsoma**
A simple implementation of captions based on the current implementation of plot titles.  I know that in #177 you felt it should wait until matplotlib got its act together, but for my use case I'm required to cite data sources here's hoping.

**Basic usage**

```python
(
    ggplot(df, aes(x='continent'))
    + geom_bar()
    + labs(caption="This is a sample caption")
)
```

**Example output**

caption with x-axis label

caption without x-axis label

caption with default legend

**Customization**

You can also specify the appropriate theme options through `element_text` customize the caption.

```python
(
    ggplot(df, aes(x='continent', color='continent'))
    + geom_bar()
    + labs(caption="This is a sample caption\nacross lines", x="")
    + theme(caption=element_text(
        size=8,
        margin={'r': -120, 't': -30}
    ))
)
```

advanced usage with options, size, and margin

### CODE REVIEW

**Comment by jwhendy** [comment]
I just cloned your branch and used this. Very nice! I skimmed the code and can't tell from the comments on #177 and reference to #46 what the pros/cons of  achieving this your way vs. whatever would be preferred re. a Layout Manager (I'm not experienced enough with matplotlib internals)... however from a practical standpoint, this worked great!

**Comment by jsoma** [comment]
I'd say the cons of doing it my way are that it's a bespoke function that isn't terribly elegant, and I'm sure there are edge cases where it doesn't work well. I think "it works with matplotlib as it stands now" is probably the only pro!

**Comment by jwhendy** [comment]
Forgive that I haven't dug in to the existing `labs(title = ...)` or your "bespoke function" as you put it, but is the point that plotnine uses something built-in to matplotlib and your function doesn't? Or that `title` is using something "proper" but you're hacking matplotlib?

I just looked around and noted [`suptitle`](https://stackoverflow.com/questions/1388450/giving-graphs-a-subtitle-in-matplotlib) and [`figtext`](https://stackoverflow.com/questions/34010205/adding-caption-below-x-axis-for-a-scatter-plot-using-matplotlib) as things matplotlib provides... is this general desire for all of titles, subtitles, and captions eventually going to be accomplished through matplotlib mechanisms, or is the point that something entirely new is in the works and being built?

**Comment by quadrismegistus** [comment]
Thank you for this! Being able to cite/caption plots is a must in my field as well so this is a godsend.

**Comment by has2k1** [comment]
@jsoma, thank you for getting started on this. It is not perfect, it can require some finicky fiddling with values, but it is definitely usable.

**Pull request merged**
