### PR TITLE
Plotnine warnings cherry

### PR DESCRIPTION
**Pull request by TyberiusPrime**
This PR introduces a new Warning class PlotNineWarning,
which is now used throughout the plotnine code base when emitting warnings

It allows the downstream to capture PlotNine warnings in a structured way.

Note that PlotNine will still emit UserWarnings from upstream  - they are not being rewritten.

I've also promoted PlotNineException and PlotNineWarning to top-level objects on 
the module, so they're visible to the user.

### CODE REVIEW

**Comment by has2k1** [comment]
This makes sense, just a few issues.

- `PlotnineWarning` not `PlotNineWarning`
- `PlotnineException` and `PlotnineWarning` should not be elevated to the top level. Their main target is developers using plotnine not users for the library. They are fine at `plotnine.exceptions`.

**Comment by TyberiusPrime** [comment]
> * `PlotnineWarning` not `PlotNineWarning`
I hang my head in shame.

> * `PlotnineException` and `PlotnineWarning` should not be elevated to the top level. Their main target is developers using plotnine not users for the library. They are fine at `plotnine.exceptions`.
As you wish.

I've updated the PR accordingly.

**Comment by has2k1** [comment]
Need to fix the lint errors. The other tests are failing for a different reason.

**Comment by TyberiusPrime** [comment]
Ok, cool. Will integrate flake8 in my further workflow.
Fixed the two unrelated lint warnings as well while I was at it.

**Comment by has2k1** [comment]
I think Matplotlib is not being installed properly. I have no clue why, even the previously passing tests are failing!

```python
...
    import matplotlib.units as units
  File "/home/travis/miniconda/envs/plotnine-test/lib/python3.6/site-packages/matplotlib/__init__.py", line 1111, in <module>
    rcParamsOrig = RcParams(rcParams.copy())
  File "/home/travis/miniconda/envs/plotnine-test/lib/python3.6/site-packages/matplotlib/__init__.py", line 891, in __getitem__
    from matplotlib import pyplot as plt
  File "/home/travis/miniconda/envs/plotnine-test/lib/python3.6/site-packages/matplotlib/pyplot.py", line 32, in <module>
    import matplotlib.colorbar
  File "/home/travis/miniconda/envs/plotnine-test/lib/python3.6/site-packages/matplotlib/colorbar.py", line 28, in <module>
    import matplotlib.artist as martist
AttributeError: module 'matplotlib' has no attribute 'artist'
```

**Comment by TyberiusPrime** [comment]
Possibly something in connection with the recent github outage?
It also claims 'all checks have failed' when the last one (lint) passes.

I have all pytest test cases passing locally, except for the xkcd one, which is a font issue on my machine.
But it's very verbose, with a ton of PendingDeprecationWarnings and the like (which again might be a local issue, though this is a fresh virtualenv).

**Comment by TyberiusPrime** [comment]
Do I need to push a no-change commit to retrigger the checks?

**Comment by has2k1** [comment]
> Do I need to push a no-change commit to retrigger the checks?

No need. I can restart the tests on travis. MPL is fixed but `patsy` is still broken.

**Comment by TyberiusPrime** [comment]
I ran it in a local travis-ci clone, the test_geom_quantile (patsy error) passes there - but I get a different error with geom_map_tests/test_geometries, same one as in #220.

I suspect that one is an issue with geopandas failing to read the created shp file, or perhaps shapefile failing to write a valid shp file, either way, the GeoSeries contains None which of course has no .bounds.

**Comment by TyberiusPrime** [comment]
Ok, so I have it down to this, where test.shp has been written by test_geom_map._create_test_input_files
fiona is what geopandas uses to read the shp file.

```python
>>> import fiona
>>> op = fiona.open("test.shp")
>>> list(op)
ERROR 1: Error in fread() reading object of size 136 at offset 212 from .shp file
ERROR 1: Error in fread() reading object of size 120 at offset 348 from .shp file
ERROR 1: Error in fread() reading object of size 216 at offset 468 from .shp file
[{'type': 'Feature', 'id': '0', 'properties': OrderedDict([('name', 'point1')]), 'geometry': {'type': 'Point', 'coordinates': (0.0, 0.0)}}, {'type': 'Feature', 'id': '1', 'properties': OrderedDict([('name', 'point2')]), 'geometry': {'type': 'Point', 'coordinates': (0.0, 1.0)}}, {'type': 'Feature', 'id': '2', 'properties': OrderedDict([('name', 'point3')]), 'geometry': {'type': 'Point', 'coordinates': (1.0, 1.0)}}, {'type': 'Feature', 'id': '3', 'properties': OrderedDict([('name', 'point4')]), 'geometry': {'type': 'Point', 'coordinates': (1.0, 0.0)}}, {'type': 'Feature', 'id': '4', 'properties': OrderedDict([('name', 'polygon1')]), 'geometry': None}, {'type': 'Feature', 'id': '5', 'properties': OrderedDict([('name', 'polygon2')]), 'geometry': None}, {'type': 'Feature', 'id': '6', 'properties': OrderedDict([('name', 'line1')]), 'geometry': None}]
```
(note the None geometrys, which trip up later.)

**Comment by TyberiusPrime** [comment]
I have tried. Haven't worked with git rebase much so far - our own workflow is based on mercurial and merging. Let's see if this worked.

**Comment by has2k1** [comment]
Rebasing should have been easier, but the problem is you had worked on top of my dev branch, which I rebase often before the changes show up in master. The `dev` branch is public only because I want travis to test it to run on it.

For future pull requests always work on top of master.

**Pull request closed without merging**
